spring:
  application:
     name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dd1-auto: name
    show-sql: false
