global:
   message: Welcome to customer service dev enviroment!!
server:
  port: 8082
message: Hellow from prod!
spring:
  database:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password: chandra
jpa:
  hibernate:
     ddl-auto: update
  show-sql: true
