global:
  message: Welcome to customer servcie prod environment!!
server:
  port: 8083
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password:
jpa: 
  hibernate:
    dd1-auto: update
  show-sql: true
