global:
  message: Welcome to customer servcie dev environment!!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password:
jpa: 
  hibernate:
    dd1-auto: update
  show-sql: false
