global:
  message: Welcome to order servcie prod environment!!
server:
  port: 8085
message: Hello from order Prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password:
jpa: 
  hibernate:
    dd1-auto: update
  show-sql: true
