global:
   message: Welcome to order service dev enviroment!!
server:
  port: 8082
message: Hellow from order Dev!
spring:
  database:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: chandra
jpa:
  hibernate:
     ddl-auto: update
  show-sql: true
