global:
  message: Welcome to order servcie dev environment!!
server:
  port: 8084
message: Hello from order Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password:
jpa: 
  hibernate:
    dd1-auto: update
  show-sql: true
